### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by dennisbrouwer91** [mnederlof/com.ubnt.unifi#14]
Hi,

I can see version 1.0.0 is on Github, but i'm unable to see it in the Homey app store to update. I really want that reconnect thingy.
Are you going to release it to the app store anytime soon?

Regards,
Dennis

**Comment by mnederlof** [comment]
Don't be so impatient... :-)

It has already been submitted and is pending review by athom before it is updated in the app store.
