### ISSUE TITLE
Homey Desktop App does not relay realtime events?

### ISSUE THREAD

**Issue by mnederlof** [mnederlof/com.ubnt.unifi#2]
When using the Homey App, it seams like it is not capable of using the realtime events sent from the driver to the settings page?

**Comment by Vonkenboer** [comment]
There is a delay caused by the Unifi controller. I checked with the Homey Logger App and the Homey Android App. When controller report a disconnect state it is right reported in the Homey and also to the Homey App.

Seems OK to me.

**Comment by mvl64** [comment]
Hi Michel,
I was going to file an issue on this too - I love the app, it seems stable and reliable but somehow there is always about 10 minutes delay on updates reported on Homey (compared to the updates in the Cloudkey, which really represent realtime changes).
What I don't understand is the unifi app connects about 180 times per minute ( on average), how come it keeps reporting an "outdated" status ? (as mentioned, the cloudkey events view shows a device is disconnected and about 10 minutes later the same device is reported offline on Homey. Does the cloudkey have different statuses ?)
