### ISSUE TITLE
[Feature request] add trigger signal percentage 

### ISSUE THREAD

**Issue by robiebab** [mnederlof/com.ubnt.unifi#20]
i'm missing the signal trigger, then i can use it to detect it if i'm upstairs or downstairs

**Comment by mnederlof** [comment]
@robiebab , what would the trigger then be?  if signal if below some configurable threshold, then it would trigger all the time, so that would not be good.

**Comment by robiebab** [comment]
The trigger would be the signal changes in percentage. for example percentage: 60% to 67%, you can set in the and collum if bigger or smaller etc.
