### ISSUE TITLE
The triggers First device is connected and Last device has disconnected are not working

### ISSUE THREAD

**Issue by AlbertDijksma** [mnederlof/com.ubnt.unifi#24]
Hi,
The triggers First device is connected and Last device has disconnected are not working.
My setup:
Homey Firmware Version: 1.5.6
UniFi app version V2.0.2
Unifi cloud key controller version: 5.6.30

Kind regards,
Albert

**Comment by mnederlof** [comment]
Thanks for reporting, this issue is fixed in the next release.

**Comment by AlbertDijksma** [comment]
Hi,
Version 2.0.3 works well.
Thanks for the quick response.

Kind regards,
Albert

**Comment by AlbertDijksma** [comment]
I forget to report something.
This Sdk2 version is very stable.
I have no more connection problems with the controller.

**Comment by mnederlof** [comment]
Thanks @AlbertDijksma , good to know the connection problems are solved with the new library.
