### ISSUE TITLE
StatusCodeError: 401 when connecting to Ubiquity Controller (5.7.20)

### ISSUE THREAD

**Issue by fhuijbreghs** [mnederlof/com.ubnt.unifi#25]
Connecting to my Ubiquity Controller (5.7.20) gives me this "StatusCodeError: 401" error:

2018-3-19 08:03:37 : [debug] Updating status to Disconnected
2018-3-19 08:03:37 : [debug] StatusCodeError: 401 - {"data":[],"meta":{"msg":"api.err.NoSiteContext","rc":"error"}}
2018-3-19 08:03:37 : [debug] Error while fetching usergroup list
2018-3-19 08:03:37 : [debug] Updating status to Disconnected
2018-3-19 08:03:37 : [debug] Error:   RangeError: Invalid WebSocket frame: RSV1 must be clear
2018-3-19 08:03:37 : [debug] Updating status to Disconnected
2018-3-19 08:03:37 : [debug] StatusCodeError: 401 - {"data":[],"meta":{"msg":"api.err.NoSiteContext","rc":"error"}}
2018-3-19 08:03:37 : [debug] Error while fetching ap list
2018-3-19 08:03:37 : [debug] Updating status to Disconnected
2018-3-19 08:03:37 : [debug] StatusCodeError: 401 - {"data":[],"meta":{"msg":"api.err.NoSiteContext","rc":"error"}}
2018-3-19 08:03:36 : [debug] Error while fetching client list:
2018-3-19 08:03:36 : [debug] Fetching user group list
2018-3-19 08:03:36 : [debug] Updating status to Connected
2018-3-19 08:03:36 : [debug] Connection success!
2018-3-19 08:03:35 : [debug] Updating unifi connection params.
2018-3-19 08:03:35 : [debug] Updating status to Connecting
2018-3-19 08:03:35 : [debug] Connecting to unifi controller 192.168.3.20

**Comment by AlbertDijksma** [comment]
on my system with 5.7.20 controler and Homey Firmware Versie: 1.5.8 no issues.

**Comment by fhuijbreghs** [comment]
It works after change the site name in the "Ubiquiti UniFi Instellingen" from "MySite" (actual site name) to "default".
