### ISSUE TITLE
Problem with clients count Unifi controller 5.8.30 Windows and Homey 1.5.12

### ISSUE THREAD

**Issue by mattiassvahn** [mnederlof/com.ubnt.unifi#28]
In debug view "Clients connected: before:3, now:3 " but in kontroller webgui 34 client on wireless.
9/27/2018, 7:34:52 PM : [debug] Accesspoint AP-LR 1 (xx) has 1 clients
9/27/2018, 7:34:52 PM : [debug] Accesspoint AP-Lite 1 (xx) has 0 clients
9/27/2018, 7:34:52 PM : [debug] Accesspoint AP-Lite 2 (xx) has 2 clients
9/27/2018, 7:34:52 PM : [debug] Accesspoint AP-Lite 3 (xx) has 0 clients
Unifi system has 3 AC Lite and 1 AC-LR.

**Comment by McAndersDK** [comment]
I have the same issue, same controller version, but Linux version of the controller.

**Comment by mnederlof** [comment]
That's not a bug. The client count is the number of wifi clients  which have been associated with homey

**Comment by McAndersDK** [comment]
Right you are, atleast for my issue :) Very nice!!
