### ISSUE TITLE
[Minor bug] Unifi controller site name is not accepted, 'default' is.

### ISSUE THREAD

**Issue by Vonkenboer** [mnederlof/com.ubnt.unifi#3]
First of all, very, very nice job you did! Thumbs up!

Just a minor bug report, though:

When changing the site name, in the (your) Homey app, to the actual name used in the Unifi controller, connections are refused. Changing it to 'default' again solves the problem.

Keep on the good work!

**Comment by acefed** [comment]
This is not a bug, this is the way UniFi allows access to the Controller over the network. The name is required for constructing URLs, for example:

https://127.0.0.1:8443/manage/site/default/dashboard

For a first site it is 'default'. If you add more sites, this part in the URL will change. That's the part Homey needs for connecting.

**Comment by Dijker** [comment]
Great Work, Thanks!!
I migrated my Controller to a new install on a Raspberry Pi, 
The Export is imported as a new Site, 
Couldn't get it to work, until i Read above link.

The Site name is obfuscated in the URL, so My Site NameX is  changed in the URL to 
https://10.1.2.3:8443/manage/site/**oy7g8bp9**/settings/site

So maybe change Site: to Site Code* : 
with an note: *: Site is default or the label/folder below site in the URL.
