### ISSUE TITLE
A lot of login messages after Controller update to version 5.9.29

### ISSUE THREAD

**Issue by arthurpoortman** [mnederlof/com.ubnt.unifi#31]
Since the update of the Unifi controller to version 5.9.29 (coming from 5.8.00) i see a lot of login messages in the Events log on the controller from the account that  is used for the App, about 10-20 logins per minute.
I see no errors in the debug log of Homey., for now i disabled the app.

Best regards,

Arthur

**Comment by nombz** [comment]
I bet that this is related to what I am seeing. I have a flow that triggers on a "DEvice just connected" and the filtered on a name and when that triggers a "Voice command" on Homey that welcomes the owner of the mobile that just connected home. After upgrace to 5.9.29 homey now greets the person with about 10-20 messages.

**Comment by mnederlof** [comment]
As i do not have discovered this issue just yet, i cannot reproduce and have to close this issue for now.
