### ISSUE TITLE
Not reporting correct connect information on 2.0.0-RC2 of Homey

### ISSUE THREAD

**Issue by mhoogenbosch** [mnederlof/com.ubnt.unifi#32]
Since I have upgraded to firmware 2.0.0-RC1 (and RC2) the Wifi clients don't get connected anymore. When filtering on a disconnect, it works. But creating an action on AP change or a Connect action it doesn't do anything.

**Comment by mnederlof** [comment]
for some reason i cannot upgrade to firmware 2.0 yet. (expermental firmware checkbox is gone..), when i have fw 2.0 i will test this.

**Comment by mhoogenbosch** [comment]
Don’t worry, was probably an issue in the homey. Now it works
