### ISSUE TITLE
Failed to reconnect when Homey WiFi is down for longer period of time

### ISSUE THREAD

**Issue by Vonkenboer** [mnederlof/com.ubnt.unifi#4]
Hi,

When the Homey WiFi is down for a longer period of time, for example more than 30 minutes, and Homey reconnects, the Unifi app isn't reconnecting.

Only reconnects by forcing the settings again.

**Comment by konradwalsh** [comment]
I can confirm this.. if you go to apps / unifi / restart app it functions normally again. However, this has to be done each Homey reboot

**Comment by jaimevisser** [comment]
Happened when updating firmware on my unifi AP. The app should at least try reconnecting every X mins when disconnected if it connected successfully at least once with current settings.

**Comment by Veldkornet** [comment]
Can you maybe add a configurable retry interval or something?

The only way I notice that this happens is when all of my flows all of a sudden stop working
