### ISSUE TITLE
Version 5.10.17 not working :-(

### ISSUE THREAD

**Issue by maaijre1** [mnederlof/com.ubnt.unifi#40]
To bad this version is not working correct. I upgraded to 5.10.17 and now its says for 2 second connected and the disconnected . Password, Host and username are correct.

**Comment by kerkenit** [comment]
Same for 5.10.21

**Comment by mvl64** [comment]
I'm running 5.10.20-11657-1 and it's working OK.
Since Kerkenit reports an issue with 5.10.21 I'm holding of on an upgrade now.
Are there positive use cases on that version ?

**Comment by kerkenit** [comment]
🤔 strange. This is between the versions. Where can I find the login credentials @mvl64

**Comment by mvl64** [comment]
@kerkenit not sure I understand: which login credentials do you mean ?
If you mean the account data for your unifi cloudkey, you can find them in the app settings in the Homey app: choose More, apps, Unbiquiti Unifi, configure app.
There you enter the ip address, username and password (leave site ID default)

**Comment by kerkenit** [comment]
To add in the homey settings. For example my portal credentials are different from the ssh. In the Homey app it's not clear where to find the credentials. 
The debug gives me a 401 status. So I'll could be wrong.
I'm new to ubiquti (4 days up and running)

**Comment by mvl64** [comment]
> 
> If you mean the account data for your unifi cloudkey, you can find them in the app settings **in the Homey app: choose More, apps, Unbiquiti Unifi, configure app.**
> There you enter the ip address, username and password (leave site ID default)

See the steps above, in bold.
You should use the UI credentials, not the SSH details .

**Comment by kerkenit** [comment]
Do you use 2FA?
I removed the app, and saw the site is default and not Default what I wrote.

**Comment by mvl64** [comment]
No 2FA, Just user account and along password. My cloudkey can only be
accessed from local network and only from some machines.... No cloud
access.
My site is default too (with lower case d)

**Comment by Danne-J** [comment]
3ba3373c-612d-4bcb-8214-bcd192562ee4


5.10.23 (Build: atag_5.10.23_11668)

Websocket disconnected befor..

So something is up with the app
