### ISSUE TITLE
[Feature request] Add monitoring of wired devices

### ISSUE THREAD

**Issue by cbho** [mnederlof/com.ubnt.unifi#43]
Is it possible to also add monitoring of devices that are listed as wired devices by the Unifi Controller software?

Would increase the possible use-cases for monitoring and automating stuff :-)

Some examples of devices that I'd like to monitor online status for, that doesn't show up now:
- Some of my Sonos devices, as they are connected by cable
- Some other Sonos devices, that are connected within the SonosNet mesh (have their own, individual IP address in the Unifi Controller, but are classified as wired, since they are connected via a wired Sonos device)
- My NAS
- Various gateways

Even a very basic monitoring like only online yes/no (without all the statistics that Unifi Controller include) would be really great :-)

**Comment by mnederlof** [comment]
Feel free to provide some code to do this feature, as this is currently not included in the stat/sta api endpoint, so new endpoints need to be gathered for wired devices.
