### ISSUE TITLE
Issue with connected clients

### ISSUE THREAD

**Issue by dennisbrouwer91** [mnederlof/com.ubnt.unifi#46]
Hi,

The debug logs show :

> 2019-11-01 10:30:44 [log] [ManagerDrivers] [wifi-client] [debug] Accesspoint Studeerkamer (44:d9:e7:f2:dc:8e) has 1 clients
2019-11-01 10:30:44 [log] [ManagerDrivers] [wifi-client] [debug] Accesspoint Woonkamer (44:d9:e7:f2:dc:a7) has 0 clients

But on the Studeerkamer AP there are 19 clients, and on the Woonkamer 15. Feels like a bug in the driver

**Comment by mnederlof** [comment]
A client in this context is a wifi client paired with homey.
