### ISSUE TITLE
Homey can't get connection with UniFi AP-AC-LT 

### ISSUE THREAD

**Issue by HermanHSlagman** [mnederlof/com.ubnt.unifi#5]
First of all, nice that you have made this app.
Homey version: 1.1.9
In my Homey Instellingen menu
I get to from the Ubiquiti UniF Instellingen menu the messages: 
`[debug] There is no connection yet, please check your settings!`
Before I have to change the Gebruikersnaam and Wachtwoord, I get the same message.
Questions:
- what are the right username and password?
- What can I do to solve this problem?

![schermafdruk 2017-02-26 18 36 40](https://cloud.githubusercontent.com/assets/20515850/23342031/dd6abaac-fc52-11e6-8c5a-300721049225.png)

Messages after reboot Homey:
26-2-2017 19:01:57 : [debug] There is no connection yet, please check your settings!
26-2-2017 19:01:42 : [debug] There is no connection yet, please check your settings!
26-2-2017 19:01:27 : [debug] There is no connection yet, please check your settings!
26-2-2017 19:01:14 : [debug] Fatal error, not reconnecting...
26-2-2017 19:01:14 : [debug] Updating status to Offline
26-2-2017 19:01:13 : [debug] Updating status to Offline
26-2-2017 19:01:13 : [debug] **Login failed? RequestError: getaddrinfo ENOTFOUND unifi unifi:8443**
26-2-2017 19:01:07 : [debug] Updating status to Connecting...
26-2-2017 19:01:07 : [debug] Creating new controller connection
26-2-2017 19:01:07 : [debug] Options:  [object Object]
26-2-2017 19:01:03 : [debug] Driver:  [object Object]

**Comment by mnederlof** [comment]
Try to use a ip address of your controller if the unifi hostname is not working. The username and password are the same as the ones you use to login into the Unifi Controller.

Based on the messages, it says it is unable to resolve the hostname 'unifi' (which should be the hostname of your controller).
