### ISSUE TITLE
 roams to AP ...... has stopped working

### ISSUE THREAD

**Issue by nickvandergraaf** [mnederlof/com.ubnt.unifi#54]
The flow no longer turns on when I roam to an specific AP (bedroom).
I use this flow to mark a person to sleep and activate the alarm.

Homey Ubiquiti UniFi version. 2.0.4
UniFi Controller version 5.12.72
UniFi Cloudkey version 1.1.11

**Comment by Bascht74** [comment]
Same here. Are there any solutions?

Any device that roams will be reported disconnected and connected in homey fows ...

**Comment by jtebbens** [comment]
Yeah, roaming doesn't work. Trigger card for specific AP connection fails.

Homey Ubiquiti UniFi version. 2.0.4
UniFi Controller version 5.13.29
AP's: 4.3.13.11253

**Comment by nickvandergraaf** [comment]
https://community.ui.com/releases/UAP-USW-Firmware-4-3-20-11298/dc127981-4b29-46be-aca0-9272d89ec2ad

Maybe this update solves the problem!

**Comment by jtebbens** [comment]
> 
> 
> https://community.ui.com/releases/UAP-USW-Firmware-4-3-20-11298/dc127981-4b29-46be-aca0-9272d89ec2ad
> 
> Maybe this update solves the problem!

Yes confirmed. Updated the AP's to 4.3.20.11298 this morning and the roaming is resolved for me.

**Comment by Bascht74** [comment]
confirmed, too. Also updated the devices to the new firmware and roaming ist resolved for me. 

I played around with it an published a pull request for this app to make better use of the AP information in the device view, flows and tokens.
