### ISSUE TITLE
app.com.ubnt.unifi.www.missing

### ISSUE THREAD

**Issue by Veldkornet** [mnederlof/com.ubnt.unifi#6]
When making a flow, and selecting "laatste verbinding broken", you get the following:
![untitled2](https://cloud.githubusercontent.com/assets/10297361/25421678/3cf06fa6-2a5e-11e7-826f-65086c06fbf3.png)

I have UniFi 5.4.14

**Comment by cautje** [comment]
Hi, same here. Cloudcontroller 5.5.20
Van you please look at this , this is the missing link to a perfect pressence tool. THX!

**Comment by jaimevisser** [comment]
![screen shot 2017-12-22 at 17 13 06](https://user-images.githubusercontent.com/3132806/34304797-866a2f24-e73b-11e7-8d97-9b227e6bb560.png)

Still here
