### ISSUE TITLE
[FEATURE REQUEST] Add flow cards for connected/disconnected status of the app to Ubiquiti Controller

### ISSUE THREAD

**Issue by djanssen1** [mnederlof/com.ubnt.unifi#9]
Would be nice to have flow cards for connected/disconnected status of the app to Ubiquiti Controller so at least you are able to notify if something is wrong

**Comment by jaimevisser** [comment]
Is this still needed with the auto-reconnect?

**Comment by mnederlof** [comment]
@jaimevisser : No indeed, it should now always be connected. Closing issue.
